### ISSUE TITLE
OPENGL ERROR

### ISSUE THREAD

**Issue by tamalv** [jbehley/point_labeler#5] opened 2019-09-19 08:08 UTC
I was trying to run the point labeler tool, however I have found some problems when it try to run ./labeler. Everything is installed and compiled as indicated in the repo. The compilation is ok, and when I run ./labeler in /point_labeler/bin/ I get the following error:

OpenGL Context Version 3.3 core profile
GLEW initialized.
OpenGL context version: 3.3
OpenGL vendor string  : VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
temp mem size: 3.6 MB
OpenGL Error: invalid enumerant(1280)
In: /catkin_ws/src/point_labeler/src/widget/Viewport.cpp on Line: 227
terminate called after throwing an instance of 'std::runtime_error'
what():  OpenGL error detected.
Aborted (core dumped)

Then, I tried to comment the lines where there is the error: all the lines in Viewport.cpp "glow::_CheckGlError(__FILE__, __LINE__);". By doing this the tool could be opened and when I select the folder with the data to annotate (the structure is as told in the repo), the tool closes I get the following error:

OpenGL Context Version 3.3 core profile
GLEW initialized.
OpenGL context version: 3.3
OpenGL vendor string  : VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
temp mem size: 3.6 MB
Found 0 instanceable labels.
/catkin_ws/src
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown name for calibration matrix.
Aborted (core dumped)

I don't know if there is something missing in my configuration or there is another mistake somewhere that I cannot find. 

Thank you in advance for your help!

**Comment by jbehley** [comment] 2019-09-19 09:33
Hi @tamalv,

Thanks for raising this issue, since it helped me to figure out that we require at least version 4.0 of OpenGL (core profile). I just updated also the `README.md` to reflect this now.

This means that you might have to get a "real" installation of Ubuntu with appropriate graphics driver (or try to get VMWare to expose an OpenGL context with at least version 4.0). I suspect that a normal installation of Ubuntu would fix the problem. All modern GPUs support at least 4.0, since the specification is out since 2010. Intel CPU (with integrated graphics) seem also to support 4.0. So I suspect that it is not a problem of your available GPU (dedicated or integrated).


To explain why the program started after you commented the line `glow::_CheckGlError(FILE, LINE);`: OpenGL is a state-machine and after a call it can get into the "error state". After that it will not do anything useful anymore. You will only notice that something is wrong if you check for the error code, which is exactly the purpose of the commented line. Even though the program was running, I suspect that it would not correctly render something. 

The problem after you removed the line is caused by a wrong `calib.txt` in the sequence folder. Unfortunately, you have to explicitly download an updated version (see step 2 of [download instructions](http://www.semantic-kitti.org/dataset.html#download)). The `calib.txt` should then contain a line starting with `Tr:`, which is the transformation from velodyne to camera.

To fix both problems you need the following:

1. A proper version of OpenGL (core profile) at least version 4.0
2. Proper calibration files, which you can download on the KITTI Vision Benchmark website.

Let me know if you need further assistance.

**Comment by medif** [comment] 2019-09-19 19:44
HI, How did you install Glow please, i am not familiar with installing from repository

**Comment by jbehley** [comment] 2019-09-19 20:06
@medif Please follow just the instructions in the readme of this repository. `catkin deps fetch` will take care of it and download the necessary repos. (However, you can also clone the repository glow simply in the `src` folder of the catkin workspace.) It will then be build when calling `catkin build`.

**Comment by medif** [comment] 2019-09-23 15:10
Hi, Thank you for the response, in fact i am not very familiar with catkin and i am not using ROS i only need to use the labeler tool to add some features.
When following the instruction i get this error. is there any way to avoid this because it will generate other errors later

![Screenshot from 2019-09-23 09-50-20](https://user-images.githubusercontent.com/55558657/65437610-1e331880-ddf2-11e9-8af0-fc8748d7a8c9.png)

**Comment by jbehley** [comment] 2019-09-23 16:02
Please follow the instructions, which say that you have to clone catkin to the src directory:

```
cd src
git clone https://github.com/ros/catkin.git
```

This is also what the error message from catkin says...

**Comment by tamalv** [comment] 2019-09-25 06:57
Thanks @jbehley ! It worked now. There are some problems trying to do it from the virtual machine. So, from normal installation of Ubuntu and OpenGL 4 it worked. Moreover I had the wrong calibration files.

**Comment by jbehley** [comment] 2019-09-25 11:13
I will now close the issue, since the original problem seems to be solved.

@medif, open a new issue if you still have problems with building everything.

**Closed by jbehley** 2019-09-25 11:13 UTC
